from __future__ import annotations

from contextlib import suppress
from pathlib import Path

from .config import Config
from .disks import libvirt_uri_uses_remote_transport
from .lock import LockBusyError, acquire_run_lock
from .logging_json import event
from .shell import CommandResult, run
from .vms import VM

# Default fallback: virtnbdbackup writes its NBD socket here when --socketfile
# is omitted. On distros with AppArmor confining libvirt-qemu (Debian/Ubuntu)
# QEMU cannot mknod here, so prefer the per-VM domain directory when available.
FALLBACK_SCRATCH_DIR = Path("/var/tmp")  # noqa: S108 - mirrors virtnbdbackup default
FALLBACK_PROBE_SOCKET_NAME = "libvirt-backup-system-preflight.sock"

# Per-VM directory libvirt creates for each running domain. The dynamic
# libvirt-<uuid> AppArmor profile (generated by virt-aa-helper) grants
# ``"/var/lib/libvirt/qemu/domain-<id>-<short-name>/*" rw,`` and DAC sets
# 0750 libvirt-qemu:libvirt-qemu, so QEMU can bind() a socket here without
# any host policy change.
LIBVIRT_QEMU_RUNTIME_ROOT = Path("/var/lib/libvirt/qemu")
BACKUP_SOCKET_NAME = "vnbd.sock"  # short enough to stay under sun_path 108B
PROBE_SOCKET_NAME = "vnbd-preflight.sock"

# Mirrors libvirt's ``VIR_DOMAIN_SHORT_NAME_MAX`` (src/conf/domain_conf.c).
# Both the on-disk directory name and the generated AppArmor rule come from
# ``virDomainDefGetShortName`` which formats as ``"%d-%.*s"`` with this width,
# so the same truncation must be applied here for long-named VMs to match.
VIR_DOMAIN_SHORT_NAME_MAX = 20

# Linux unix-socket sun_path is 108 bytes including the NUL terminator.
SUN_PATH_MAX = 107

# Schemes we cannot meaningfully probe: remote URIs would create the socket on
# the hypervisor host (whose filesystem we cannot stat from here), and test://
# does not implement nbd_server_start.
SKIP_PROBE_URI_PREFIXES = ("test://", "test:///")


def _uses_local_system_qemu(uri: str) -> bool:
    return uri in {"qemu:///system", "qemu+unix:///system"}


def _virsh_hmp(uri: str, vm_name: str, command: str) -> CommandResult:
    return run(
        ["virsh", "-c", uri, "qemu-monitor-command", "--hmp", "--", vm_name, command],
        check=False,
    )


def domain_socket_path(uri: str, vm_name: str, *, basename: str = BACKUP_SOCKET_NAME) -> Path | None:
    """Return the libvirt per-VM NBD socket path, or ``None`` when not usable.

    On stock Debian/Ubuntu the per-VM ``libvirt-<uuid>`` AppArmor profile
    grants ``domain-<id>-<short-name>/* rw`` (generated by virt-aa-helper) and
    the directory is ``0750 libvirt-qemu:libvirt-qemu`` at DAC, so QEMU can
    bind a socket inside ``/var/lib/libvirt/qemu/domain-<id>-<vm>/`` without
    any host policy change — unlike the ``/var/tmp/virtnbdbackup.*`` default
    which is DAC-open but AppArmor-blocked.

    Restricted to local system qemu URIs: the session URI keeps its per-VM dirs
    under the user's XDG cache, not ``/var/lib/libvirt/qemu/``, so the system
    path we would compute does not even exist for session domains.

    Returns ``None`` (caller should let virtnbdbackup fall back to its own
    ``/var/tmp`` default, after which a missing AppArmor rule will surface as
    the usual ``Permission denied``) when any of these hold: non-system URI,
    ``virsh domid`` fails or returns ``-``, the domain directory is missing
    or not stat-able by the caller, or the resulting socket path would exceed
    Linux's ``sun_path`` limit (108 bytes incl. NUL) where ``bind()`` would
    fail at runtime.
    """
    if not _uses_local_system_qemu(uri):
        return None
    try:
        result = run(["virsh", "-c", uri, "domid", "--", vm_name], check=False)
    except OSError:
        return None
    if result.returncode != 0:
        return None
    domid = result.stdout.strip()
    if not domid.isdigit():
        return None
    short_name = vm_name[:VIR_DOMAIN_SHORT_NAME_MAX]
    candidate = LIBVIRT_QEMU_RUNTIME_ROOT / f"domain-{domid}-{short_name}" / basename
    if len(str(candidate).encode("utf-8")) > SUN_PATH_MAX:
        return None
    try:
        if not candidate.parent.is_dir():
            return None
    except OSError:
        # ``is_dir`` raises ``PermissionError`` (a ``OSError`` subclass) when
        # the parent dir's ``stat`` is denied — e.g. running unprivileged
        # while libvirt-qemu owns ``/var/lib/libvirt/qemu/`` at 0750. Treat
        # that the same as missing: the caller falls back to /var/tmp.
        return None
    return candidate


def virtnbdbackup_socket_args(uri: str, vm_name: str) -> list[str]:
    """Return ``["-f", <path>]`` when the per-VM domain socket path is usable.

    Wrapper used by ``backup_vm`` to route the NBD socket through the libvirt
    per-VM directory: virtnbdbackup's default ``/var/tmp/virtnbdbackup.<pid>``
    is DAC-open but blocked by QEMU's AppArmor profile on stock Debian/Ubuntu,
    while ``/var/lib/libvirt/qemu/domain-*/`` is granted by the same profile.
    A stale socket from a partial prior run is unlinked best-effort first;
    returns ``[]`` when discovery fails so callers fall back to the default.
    """
    path = domain_socket_path(uri, vm_name)
    if path is None:
        return []
    with suppress(OSError):
        path.unlink(missing_ok=True)
    return ["-f", str(path)]


def _resolve_probe_path(uri: str, vm_name: str) -> Path:
    domain_path = domain_socket_path(uri, vm_name, basename=PROBE_SOCKET_NAME)
    if domain_path is not None:
        return domain_path
    return FALLBACK_SCRATCH_DIR / FALLBACK_PROBE_SOCKET_NAME


def _classify_probe_result(result: CommandResult, vm_name: str, socket_path: Path) -> list[str]:
    output = f"{result.stderr}\n{result.stdout}"
    if "Permission denied" in output:
        # nbd_server_start (HMP) only fails this way when QEMU itself cannot
        # bind() the socket. The CLI runs as root and the parent dir is
        # writable for libvirt-qemu, so this almost always means AppArmor or
        # SELinux denies libvirt-qemu writes at the chosen path.
        return [
            f"QEMU cannot bind NBD socket at {socket_path} "
            f"(probe vm={vm_name!r}). Likely cause: AppArmor or SELinux denies "
            "libvirt-qemu writes there. On Debian/Ubuntu, allow the path via "
            "/etc/apparmor.d/local/abstractions/libvirt-qemu and reload."
        ]
    if result.returncode != 0:
        return [
            f"QEMU NBD socket bind probe failed (vm={vm_name!r}, "
            f"returncode={result.returncode}): {(result.stderr or result.stdout).strip()}"
        ]
    return []


def _cleanup(uri: str, vm_name: str, socket_path: Path, *, started: bool) -> None:
    # nbd_server_stop must only run when our nbd_server_start succeeded. If a
    # concurrent virtnbdbackup is already driving QEMU's NBD server on this
    # VM, our start fails (the slot is single-shot) and issuing stop here
    # would tear that backup's server out from under it. ``started`` is keyed
    # off ``rc==0`` from our start call, so this branch only fires when we
    # know we own the server.
    if started:
        with suppress(OSError):
            _virsh_hmp(uri, vm_name, "nbd_server_stop")
    with suppress(OSError):
        socket_path.unlink(missing_ok=True)


def probe_qemu_socket_bind(config: Config, vms: list[VM]) -> list[str]:
    """Return preflight failure messages if QEMU cannot bind an NBD socket.

    Probes at the same path ``backup_vm`` would actually use: the per-VM
    libvirt domain directory when discoverable, otherwise virtnbdbackup's
    ``/var/tmp`` default. Skipped when there is no suitable probe target
    (no running VMs, remote libvirt transport, or the test driver).

    Caller must hold the run lock: the probe drives QEMU's HMP
    ``nbd_server_start``/``nbd_server_stop`` directly, which would clash with
    a concurrent ``virtnbdbackup`` using the same slot.
    """
    uri = config.get("LIBVIRT_URI")
    if any(uri.startswith(prefix) for prefix in SKIP_PROBE_URI_PREFIXES):
        return []
    if libvirt_uri_uses_remote_transport(uri):
        event("info", "QEMU NBD socket bind probe skipped (remote libvirt URI)", uri=uri)
        return []
    target = next((vm for vm in vms if vm.running), None)
    if target is None:
        # Without a running QEMU there is no monitor to talk to. The same
        # failure mode would still hit ``run`` once a VM is started, but a
        # preflight that depends on running VMs would block every cold-start
        # workflow — so log and continue rather than fail the check.
        event("info", "QEMU NBD socket bind probe skipped (no running VMs)")
        return []
    socket_path = _resolve_probe_path(uri, target.name)
    try:
        socket_path.unlink(missing_ok=True)
    except OSError as exc:
        return [f"QEMU NBD socket bind probe could not clean stale socket {socket_path}: {exc}"]
    try:
        result = _virsh_hmp(uri, target.name, f"nbd_server_start unix:{socket_path}")
    except OSError as exc:
        return [f"QEMU NBD socket bind probe failed to invoke virsh: {exc}"]
    failures = _classify_probe_result(result, target.name, socket_path)
    _cleanup(uri, target.name, socket_path, started=result.returncode == 0)
    return failures


def probe_qemu_socket_bind_with_lock(config: Config, vms: list[VM], *, lock_held: bool) -> list[str]:
    # Lock-gated wrapper around ``probe_qemu_socket_bind``: the probe drives
    # QEMU HMP nbd_server_start/stop directly and would tear down a concurrent
    # virtnbdbackup's NBD server. ``run`` already holds the lock; standalone
    # check/doctor try-acquire and skip on busy.
    if lock_held:
        return probe_qemu_socket_bind(config, vms)
    try:
        with acquire_run_lock(config):
            return probe_qemu_socket_bind(config, vms)
    except LockBusyError as exc:
        event("info", "QEMU NBD socket bind probe skipped (another run in progress)", lock_path=str(exc.path))
        return []
